In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)

In [2]:
SCORECARD_PARAMS = {
    "target": "default12",
    "time_col": "period",
    "id_col": "aid",
    "train_end_period": "198412",
    "valid_start_period": "198501",
    "ncategories_int": 4,
    "minimum_share_int": 0.03,
    "symbol_missing": "Missing",
    "symbol_other": "<OTHERS>",
    "ncategories_nom": 4,
    "category_order": False,
    "iv_min": 0.02,
    "gini_min": 0.05,
    "psi_max": 0.25,
    "ar_diff_max": 0.20,
    "pvalue_max": 0.05,
    "vif_max": 5.0,
    "pearson_max": 0.7,
    "ar_diff_model_max": 0.10,
    "factor": 20 / np.log(2),
    "offset": 600 - (20 / np.log(2)) * np.log(50),
    "woe_epsilon": 1e-4,
    "tree_random_state": 1234,
}

In [3]:
abt_app = pd.read_parquet("../data/04_feature/abt_app.parquet")
decisions = pd.read_parquet("../data/04_feature/decisions.parquet")

In [4]:
abt_app[abt_app['default3'] == 1]

,cid,aid,product,period,act_age,act_cc,act_loaninc,app_income,app_loan_amount,app_n_installments,app_number_of_children,app_spendings,app_installment,app_char_branch,app_char_gender,app_char_job_code,app_char_marital_status,app_char_city,app_char_home_status,app_char_cars,act_call_cc,act_cins_n_loan,act_ccss_n_loan,act_call_n_loan,ags3_Mean_CMaxI_Days,agr3_Mean_CMaxI_Days,ags3_Max_CMaxI_Days,agr3_Max_CMaxI_Days,ags3_Min_CMaxI_Days,agr3_Min_CMaxI_Days,ags6_Mean_CMaxI_Days,agr6_Mean_CMaxI_Days,ags6_Max_CMaxI_Days,agr6_Max_CMaxI_Days,ags6_Min_CMaxI_Days,agr6_Min_CMaxI_Days,ags9_Mean_CMaxI_Days,agr9_Mean_CMaxI_Days,ags9_Max_CMaxI_Days,agr9_Max_CMaxI_Days,ags9_Min_CMaxI_Days,agr9_Min_CMaxI_Days,ags12_Mean_CMaxI_Days,agr12_Mean_CMaxI_Days,ags12_Max_CMaxI_Days,agr12_Max_CMaxI_Days,ags12_Min_CMaxI_Days,agr12_Min_CMaxI_Days,ags3_Mean_CMaxI_Due,agr3_Mean_CMaxI_Due,ags3_Max_CMaxI_Due,agr3_Max_CMaxI_Due,ags3_Min_CMaxI_Due,agr3_Min_CMaxI_Due,ags6_Mean_CMaxI_Due,agr6_Mean_CMaxI_Due,ags6_Max_CMaxI_Due,agr6_Max_CMaxI_Due,ags6_Min_CMaxI_Due,agr6_Min_CMaxI_Due,ags9_Mean_CMaxI_Due,agr9_Mean_CMaxI_Due,ags9_Max_CMaxI_Due,agr9_Max_CMaxI_Due,ags9_Min_CMaxI_Due,agr9_Min_CMaxI_Due,ags12_Mean_CMaxI_Due,agr12_Mean_CMaxI_Due,ags12_Max_CMaxI_Due,agr12_Max_CMaxI_Due,ags12_Min_CMaxI_Due,agr12_Min_CMaxI_Due,ags3_Mean_CMaxC_Days,agr3_Mean_CMaxC_Days,ags3_Max_CMaxC_Days,agr3_Max_CMaxC_Days,ags3_Min_CMaxC_Days,agr3_Min_CMaxC_Days,ags6_Mean_CMaxC_Days,agr6_Mean_CMaxC_Days,ags6_Max_CMaxC_Days,agr6_Max_CMaxC_Days,ags6_Min_CMaxC_Days,agr6_Min_CMaxC_Days,ags9_Mean_CMaxC_Days,agr9_Mean_CMaxC_Days,ags9_Max_CMaxC_Days,agr9_Max_CMaxC_Days,ags9_Min_CMaxC_Days,agr9_Min_CMaxC_Days,ags12_Mean_CMaxC_Days,agr12_Mean_CMaxC_Days,ags12_Max_CMaxC_Days,agr12_Max_CMaxC_Days,ags12_Min_CMaxC_Days,agr12_Min_CMaxC_Days,ags3_Mean_CMaxC_Due,agr3_Mean_CMaxC_Due,ags3_Max_CMaxC_Due,agr3_Max_CMaxC_Due,ags3_Min_CMaxC_Due,agr3_Min_CMaxC_Due,ags6_Mean_CMaxC_Due,agr6_Mean_CMaxC_Due,ags6_Max_CMaxC_Due,agr6_Max_CMaxC_Due,ags6_Min_CMaxC_Due,agr6_Min_CMaxC_Due,ags9_Mean_CMaxC_Due,agr9_Mean_CMaxC_Due,ags9_Max_CMaxC_Due,agr9_Max_CMaxC_Due,ags9_Min_CMaxC_Due,agr9_Min_CMaxC_Due,ags12_Mean_CMaxC_Due,agr12_Mean_CMaxC_Due,ags12_Max_CMaxC_Due,agr12_Max_CMaxC_Due,ags12_Min_CMaxC_Due,agr12_Min_CMaxC_Due,ags3_Mean_CMaxA_Days,agr3_Mean_CMaxA_Days,ags3_Max_CMaxA_Days,agr3_Max_CMaxA_Days,ags3_Min_CMaxA_Days,agr3_Min_CMaxA_Days,ags6_Mean_CMaxA_Days,agr6_Mean_CMaxA_Days,ags6_Max_CMaxA_Days,agr6_Max_CMaxA_Days,ags6_Min_CMaxA_Days,agr6_Min_CMaxA_Days,ags9_Mean_CMaxA_Days,agr9_Mean_CMaxA_Days,ags9_Max_CMaxA_Days,agr9_Max_CMaxA_Days,ags9_Min_CMaxA_Days,agr9_Min_CMaxA_Days,ags12_Mean_CMaxA_Days,agr12_Mean_CMaxA_Days,ags12_Max_CMaxA_Days,agr12_Max_CMaxA_Days,ags12_Min_CMaxA_Days,agr12_Min_CMaxA_Days,ags3_Mean_CMaxA_Due,agr3_Mean_CMaxA_Due,ags3_Max_CMaxA_Due,agr3_Max_CMaxA_Due,ags3_Min_CMaxA_Due,agr3_Min_CMaxA_Due,ags6_Mean_CMaxA_Due,agr6_Mean_CMaxA_Due,ags6_Max_CMaxA_Due,agr6_Max_CMaxA_Due,ags6_Min_CMaxA_Due,agr6_Min_CMaxA_Due,ags9_Mean_CMaxA_Due,agr9_Mean_CMaxA_Due,ags9_Max_CMaxA_Due,agr9_Max_CMaxA_Due,ags9_Min_CMaxA_Due,agr9_Min_CMaxA_Due,ags12_Mean_CMaxA_Due,agr12_Mean_CMaxA_Due,ags12_Max_CMaxA_Due,agr12_Max_CMaxA_Due,ags12_Min_CMaxA_Due,agr12_Min_CMaxA_Due,act3_n_arrears,act3_n_arrears_days,act3_n_good_days,act6_n_arrears,act6_n_arrears_days,act6_n_good_days,act9_n_arrears,act9_n_arrears_days,act9_n_good_days,act12_n_arrears,act12_n_arrears_days,act12_n_good_days,act_cins_n_loans_act,act_cins_maxdue,act_cins_min_pninst,act_cins_min_lninst,act_cins_utl,act_cins_dueutl,act_cins_cc,act_cins_seniority,act_cins_min_seniority,act_cins_n_loans_hist,act_cins_n_statC,act_cins_n_statB,act_ccss_n_loans_act,act_ccss_maxdue,act_ccss_min_pninst,act_ccss_min_lninst,act_ccss_utl,act_ccss_dueutl,act_ccss_cc,act_ccss_seniority,act_ccss_min_seniority,act_ccss_n_loans_hist,act_ccss_n_statC,act_ccss_n_statB,act_cus_active,default3,default6,default12
0,0000000625,css1975010100063,css,197501,55.0,0.629712,1.583782,3157.0,5000.0,24.0,2.0,1780.0,208.0,Empty,Female,Permanent,Maried,Small,Owner,Owner,0.629712,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
3,0000002366,css1975010100123,css,197501,70.0,0.559242,3.949447,1266.0,5000.0,24.0,0.0,500.0,208.0,Empty,Female,Retired,Maried,Medium,Owner,Owner,0.559242,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
5,0000000088,css1975010200010,css,197501,62.0,0.745138,5.117707,977.0,5000.0,24.0,0.0,520.0,208.0,Empty,Male,Retired,Maried,Big,Owner,Owner,0.745138,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,60.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
9,0000000824,css1975010200074,css,197501,43.0,0.403859,3.215434,1555.0,5000.0,24.0,2.0,420.0,208.0,Empty,Female,Permanent,Maried,Big,Rental,Owner,0.403859,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
11,0000003161,css1975010200135,css,197501,48.0,0.329016,3.238342,1544.0,5000.0,24.0,0.0,300.0,208.0,Empty,Female,Permanent,Maried,Medium,Rental,Owner,0.329016,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49123,0000023212,ins1987121400011,ins,198712,45.0,0.325579,0.274917,8468.0,2328.0,24.0,1.0,2660.0,97.0,Fenitures,Male,Owner company,Divorced,Big,Owner,No,0.325579,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
49139,0000000172,ins1987121600033,ins,198712,85.0,0.546999,1.671574,883.0,1476.0,12.0,0.0,360.0,123.0,Radio-TV,Male,Retired,Widowed,Small,Owner,Owner,1.067950,2,0,2,12.333333,12.333333,15.0,15.0,8.0,8.0,12.833333,12.833333,15.0,15.0,8.0,8.0,13.000000,13.000000,15.0,15.0,8.0,8.0,13.000000,NaN,15.0,NaN,8.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,7.0,NaN,7.0,NaN,6.666667,NaN,7.0,NaN,6.0,NaN,12.333333,12.333333,15.0,15.0,8.0,8.0,12.833333,12.833333,15.0,15.0,8.0,8.0,13.000000,13.000000,15.0,15.0,8.0,8.0,13.000000,NaN,15.0,NaN,8.0,NaN,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.777778,0.777778,7.0,7.0,0.0,0.0,1.818182,1.818182,7.0,7.0,0.0,0.0,0,0,2,0,0,5,1,0,6,3,0,6,1.0,0.0,7.0,17.0,0.291667,0.0,0.520951,145.0,8.0,5.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.0,21.0,14.0,3.0,11.0,1.0,1.0,1.0,1.0
49142,0000001972,ins1987121700012,ins,198712,74.0,0.589574,0.907489,1362.0,1236.0,12.0,0.0,700.0,103.0,Fenitures,Male,Retired,Widowed,Small,Owner,Owner,1.805433,3,0,3,13.000000,13.000000,15.0,15.0,10.0,10.0,12.666667,12.666667,15.0,15.0,10.0,10.0,13.000000,13.000000,15.0,15.0,10.0,10.0,13.363636,13.363636,15.0,15.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.000000,13.000000,15.0,15.0,10.0,10.0,12.666667,12.666667,15.0,15.0,10.0,10.0,13.000000,13.000000,15.0,15.0,10.0,10.0,13.363636,13.363636,15.0,15.0,10.0,10.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0,0,2,0,0,4,0,0,6,0,0,6,2.0,0.0,0.0,12.0,0.375000,0.0,0.607930,19.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0
49166,0000000578,ins1987122100043,ins,198712,83.0,0.470060,4.814371,668.0,3216.0,24.0,0.0,180.0,134.0,Computers,Female,Retired,Widowed,Large,Owner,Owner,2.634731,2,2,4,13.333333,13.333333,15.0,15.0,12.0,12.0,12.666667,12.666667,15.0,15.0,11.0,11.0,11.666667,11.666667,15.0,15.0,4.0,4.0,11.666667,NaN,15.0,NaN,4.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,17.0,17.0,19.0,19.0,15.0,15.0,14.4,14.4,19.0,19.0,8.0,8.0,15.571429,NaN,20.0,NaN,8.0,NaN,15.444444,NaN,20.0,NaN,8.0,NaN,6.666667,6.666667,7.0,7.0,6.0,6.0,6.333333,6.333333,7.0,7.0,5.0,5.0,6.333333,6.333333,7.0,7.0,5.0,5.0,6.000000,6.0,7.0,7.0,4.0,4.0,15.666667,15.666667,19.0,19.0,13.0,13.0,15.000000,15.000000,19.0,19.0,13.0,13.0,14.555556,14.555556,20.0,20.0,4.0,4.0,14.636364,14.636364,20.0,20.0,4.0,4.0,6.666667,6.666667,7.0,7.0,6.0,6.0,6.333333,6.333333,7.0,7.0,5.0,5.0,6.333333,6.333333,7.0,7.0,5.0,5.0,6.000000,6.000000,7.0,7.0,4.0,4.0,3,1,1,6,1,2,9,3,3,11,3,3,1.0,0.0,8.0,16.0,0.333333,0.0,1.002994,116.0,9.0,4.0,1.0,2.0,3.0,7.0,0.0,12.0,0.25,0.166667,0.580838,112.0,4.0,12.0,2.0,7.0,1.0,1.0,1.0,1.0
49171,0000023247,ins1987122200041,ins,198712,59.0,1.331593,31.018277,383.0,11880.0,36.0,0.0,180.0,330.0,Computers,Female,Retired,Maried,Medium,Owner,Owner,1.331593,1,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0

In [5]:
abt_app['default12'].value_counts()

default12
0.0    26297
1.0    18305
Name: count, dtype: int64

In [6]:
def prepare_target(df, target="default12") -> pd.DataFrame:
    """
    Convert the target to a binary variable.
    """
    df = df.copy()
    df[target] = df[target].map({'.i': 0, '.d': 0, 0: 0, 1: 1})
    df = df.dropna(subset=[target])
    df[target] = df[target].astype(int)
    return df

In [7]:
def load_and_prepare_abt(abt_path, decision_path) -> pd.DataFrame:
    abt_app = pd.read_parquet(abt_path)
    decisions = pd.read_parquet(decision_path)
    df = abt_app.merge(decisions[['aid', 'decision', 'decline_reason']],
        on='aid', how='left')
    df = prepare_target(df)
    return df

df = load_and_prepare_abt("../data/04_feature/abt_app.parquet", "../data/04_feature/decisions.parquet")
assert "decision" in df.columns
assert "default12" in df.columns
assert df["aid"].is_unique
assert set(df["default12"].unique()) <= {0, 1}
print(df.groupby(["product", "decision"])["default12"].mean())
print("rows kept:", len(df), "bad rate:", df["default12"].mean())

product  decision
css      A           0.662746
         N           0.740232
ins      A           0.137648
Name: default12, dtype: float64
rows kept: 44602 bad rate: 0.41040760504013274

In [8]:
def get_candidate_features(df, product) -> dict:
    """
    Get the candidate features for the product.
    """
    df_dict = {}
    df = df.copy()
    df = df[df["product"] == product]
    df = df.dropna(subset=["decision", "decline_reason"])
    leakage_cols = [
    # 1. Direct Target Labels (The outcomes you are trying to predict)
    "default3",
    "default6",
    "default12",
    # 2. Post-Decision Outcomes (Determined after the model runs)
    "decision",
    "decline_reason",
    # 3. Future Performance Metrics (Behavior that happens *after* the loan is active)
    "act3_n_arrears",
    "act3_n_arrears_days",
    "act3_n_good_days",
    "act6_n_arrears",
    "act6_n_arrears_days",
    "act6_n_good_days",
    "act9_n_arrears",
    "act9_n_arrears_days",
    "act9_n_good_days",
    "act12_n_arrears",
    "act12_n_arrears_days",
    "act12_n_good_days",
    "act_cus_active",
    ]
    id_cols = ["cid", "aid", "period", "product"]
    drop_cols = [c for c in leakage_cols + id_cols if c in df.columns]
    numeric = [
        c for c in df.columns
        if pd.api.types.is_numeric_dtype(df[c])
        and not pd.api.types.is_bool_dtype(df[c])
    ]
    nominal = [
        c for c in df.columns
        if c not in numeric
        and (
        pd.api.types.is_object_dtype(df[c])
        or pd.api.types.is_string_dtype(df[c])
        or isinstance(df[c].dtype, pd.CategoricalDtype)
        or pd.api.types.is_bool_dtype(df[c])
        )
    ]
    return {
        "numeric": numeric,
        "nominal": nominal,
        "all": numeric + nominal,
    }

cand = get_candidate_features(df, "css")
assert set(cand['numeric']).isdisjoint(set(cand['nominal']))
print(f"Number of numeric features: {len(cand['numeric'])}")
print(f"Number of nominal features: {len(cand['nominal'])}")
print(f"Number of all features: {len(cand['all'])}")

Number of numeric features: 197
Number of nominal features: 13
Number of all features: 210

In [9]:
def partition_abt(df, train_end, valid_start, time_col="period") -> dict:
    """
    Partition the data into train and valid sets.
    """
    df = df.copy()
    df_train = df[df[time_col] <= train_end]
    df_valid = df[df[time_col] >= valid_start]
    return df_train, df_valid

train_end, valid_start = "198412", "198501"
df_train, df_valid = partition_abt(df, train_end, valid_start)
assert df_train["period"].max() == train_end
assert df_valid["period"].min() == valid_start
print(f"Train set: {df_train.shape}, Valid set: {df_valid.shape}")
print(f"Train set bad rate: {df_train['default12'].mean():.2%}, Valid set bad rate: {df_valid['default12'].mean():.2%}")

Train set: (34443, 210), Valid set: (10159, 210)
Train set bad rate: 42.49%, Valid set bad rate: 36.13%

In [10]:
def fit_bin_numeric(train, feature, target, params) -> dict:
    """
    Fit decision-tree bins for one numeric feature.
 
    Parameters
    ----------
    train   : DataFrame containing at least *feature* and *target* columns.
    feature : Name of the numeric predictor column.
    target  : Name of the binary (0/1) target column.
    params  : Scorecard parameter dict.  Recognised keys:
                  max_bins          - maximum leaf nodes / bins  (default 5)
                  min_bin_size      - min samples per leaf as fraction (default 0.05)
                  tree_random_state - random_state for DecisionTreeClassifier (default 42)
 
    Returns
    -------
    dict with keys
        type        : "numeric"
        feature     : feature name
        edges       : sorted list of bin edges, always starting with -inf and ending with +inf
        missing_bin : True when the raw column contained NaNs (separate bucket reserved)
    """
    from sklearn.tree import DecisionTreeClassifier
    max_bins = params.get("max_bins", 5)
    min_bin_size = params.get("min_bin_size", 0.05)
    random_state = params.get("random_state", 1234)

    has_missing = train[feature].isna().any()
    clean = train.dropna(subset=[feature, target]).copy()
    X = clean[[feature]].values
    y = clean[target].values
    
    tree = DecisionTreeClassifier(
        max_leaf_nodes=max_bins,
        min_samples_leaf=max(1, int(min_bin_size * len(clean))),
        random_state=random_state,
    )
    tree.fit(X, y)
    
    thresholds = np.unique(tree.tree_.threshold[tree.tree_.threshold != -2])
    thresholds_sorted = np.sort(thresholds)

    edges = [-np.inf] + list(thresholds_sorted) + [np.inf]

    return {
        "type": "numeric",
        "feature": feature,
        "edges": edges,
        "missing_bin": bool(has_missing)
    }

bin_num_spec = fit_bin_numeric(df_train, "app_income", "default12", SCORECARD_PARAMS)
assert bin_num_spec["type"] == "numeric"
assert bin_num_spec["feature"] == "app_income"
assert len(bin_num_spec["edges"]) == 6
assert bin_num_spec["missing_bin"] == False
print(bin_num_spec["edges"])

[-inf, np.float64(554.5), np.float64(1211.5), np.float64(1938.5), np.float64(3162.5), inf]

In [11]:
def fit_bin_nominal(train, feature, target, params) -> dict:
    """
    Fit binning for one nominal (categorical) feature.

    Steps
    -----
    1. Separate NaN rows → reserved missing label.
    2. Merge categories whose share < rare_threshold into <OTHERS>.
    3. Compute per-category event rate; sort ascending.
    4. Greedily merge adjacent-by-risk groups until count <= ncategories_nom.

    Returns
    -------
    dict with keys
        type          : "nominal"
        feature       : feature name
        category_map  : {raw_category -> group_label}   (str -> str)
        other_label   : label used for rare / unknown categories  "<OTHERS>"
        missing_label : label used for NaN values                 "<MISSING>"
    """
    other_label = params.get("other_label", "<OTHERS>")
    missing_label = params.get("missing_label", "<MISSING>")
    rare_threshold = params.get("rare_threshold", 0.02)
    max_groups = params.get("ncategories_nom", 4)

    clean = train.dropna(subset=[feature, target]).copy()
    clean["_cat_norm"] = clean[feature].astype(str)

    # identify rare categories
    freq = clean[feature].value_counts(normalize=True)
    rare_cats = set(freq[freq < rare_threshold].index)
    valid_cats = set(freq[freq >= rare_threshold].index)

    # compute event rare per valid category
    stats = (
        clean[clean[feature].isin(valid_cats)]
        .groupby(feature)[target]
        .agg(["mean", "count"])
        .rename(columns={"mean": "event_rate", "count": "n"})
        .sort_values(by="event_rate", ascending=True)
    )
    
    # merge
    groups = [[cat] for cat in stats.index]

    while len(groups) > max_groups:
        # find adjacent pair with lowest combined count to merge
        best_i, best_n = 0, float("inf")
        for i in range(len(groups) - 1):
            combined = sum(stats.loc[c, "n"] for c in groups[i] + groups[i+1])
            if combined < best_n:
                best_n, best_i = combined, i
        groups[best_i] += groups[best_i + 1]
        groups.pop(best_i + 1)
    
    # build category_map
    category_map = {}

    for idx, grp in enumerate(groups):
        label = f"G{idx+1:02d}"
        for cat in grp:
            category_map[cat] = label
    
    for cat in rare_cats:
        category_map[cat] = other_label
    
    return {
        "type": "nominal",
        "feature": feature,
        "category_map": category_map,
        "other_label": other_label,
        "missing_label": missing_label,
    }

bin_nom_spec = fit_bin_nominal(df_train, "app_char_job_code", "default12", SCORECARD_PARAMS)
assert bin_nom_spec["type"] == "nominal"
assert bin_nom_spec["feature"] == "app_char_job_code"
assert len(bin_nom_spec["category_map"]) == 4
assert bin_nom_spec["other_label"] == "<OTHERS>"
assert bin_nom_spec["missing_label"] == "<MISSING>"
print(bin_nom_spec["category_map"])

{'Permanent': 'G01', 'Owner company': 'G02', 'Retired': 'G03', 'Contract': 'G04'}

In [12]:
def fit_binning_maps(train, features, target, params) -> dict:
    """
    Dispatch to numeric or nominal bin fitter for every candidate feature.

    A column is treated as nominal when its dtype is object / category or
    when it has at most `nominal_int_threshold` (default 10) distinct integers.

    Returns
    -------
    dict  {feature_name -> bin_spec}   (train-only artifact)
    """
    nominal_int_threshold = params.get("nominal_int_threshold", 10)
    binning_maps: dict[str, dict] = {}

    for feat in features:
        col = train[feat]
        is_nominal = (
        pd.api.types.is_bool_dtype(col)
        or pd.api.types.is_object_dtype(col)
        or pd.api.types.is_string_dtype(col)
        or isinstance(col.dtype, pd.CategoricalDtype)
        or (
            pd.api.types.is_integer_dtype(col)
            and col.nunique(dropna=True) <= nominal_int_threshold
      )
    )

        if is_nominal:
            binning_maps[feat] = fit_bin_nominal(train, feat, target, params)
        else:
            binning_maps[feat] = fit_bin_numeric(train, feat, target, params)
    
    return binning_maps

sample_features = cand['all'][:3]
binning_maps = fit_binning_maps(df_train, sample_features, "default12", SCORECARD_PARAMS)
assert set(sample_features) <= set(binning_maps)
for item, key in binning_maps.items():
    print(f"{item}: {key}")

act_age: {'type': 'numeric', 'feature': 'act_age', 'edges': [-inf, np.float64(45.5), np.float64(48.5), np.float64(57.5), np.float64(75.5), inf], 'missing_bin': False}
act_cc: {'type': 'numeric', 'feature': 'act_cc', 'edges': [-inf, np.float64(0.31356000900268555), np.float64(0.5112184882164001), np.float64(0.5511272847652435), np.float64(0.6381348967552185), inf], 'missing_bin': False}
act_loaninc: {'type': 'numeric', 'feature': 'act_loaninc', 'edges': [-inf, np.float64(0.6732844710350037), np.float64(1.568779468536377), np.float64(2.379653215408325), np.float64(4.770589351654053), inf], 'missing_bin': False}

In [13]:
df_train.head()

,cid,aid,product,period,act_age,act_cc,act_loaninc,app_income,app_loan_amount,app_n_installments,app_number_of_children,app_spendings,app_installment,app_char_branch,app_char_gender,app_char_job_code,app_char_marital_status,app_char_city,app_char_home_status,app_char_cars,act_call_cc,act_cins_n_loan,act_ccss_n_loan,act_call_n_loan,ags3_Mean_CMaxI_Days,agr3_Mean_CMaxI_Days,ags3_Max_CMaxI_Days,agr3_Max_CMaxI_Days,ags3_Min_CMaxI_Days,agr3_Min_CMaxI_Days,ags6_Mean_CMaxI_Days,agr6_Mean_CMaxI_Days,ags6_Max_CMaxI_Days,agr6_Max_CMaxI_Days,ags6_Min_CMaxI_Days,agr6_Min_CMaxI_Days,ags9_Mean_CMaxI_Days,agr9_Mean_CMaxI_Days,ags9_Max_CMaxI_Days,agr9_Max_CMaxI_Days,ags9_Min_CMaxI_Days,agr9_Min_CMaxI_Days,ags12_Mean_CMaxI_Days,agr12_Mean_CMaxI_Days,ags12_Max_CMaxI_Days,agr12_Max_CMaxI_Days,ags12_Min_CMaxI_Days,agr12_Min_CMaxI_Days,ags3_Mean_CMaxI_Due,agr3_Mean_CMaxI_Due,ags3_Max_CMaxI_Due,agr3_Max_CMaxI_Due,ags3_Min_CMaxI_Due,agr3_Min_CMaxI_Due,ags6_Mean_CMaxI_Due,agr6_Mean_CMaxI_Due,ags6_Max_CMaxI_Due,agr6_Max_CMaxI_Due,ags6_Min_CMaxI_Due,agr6_Min_CMaxI_Due,ags9_Mean_CMaxI_Due,agr9_Mean_CMaxI_Due,ags9_Max_CMaxI_Due,agr9_Max_CMaxI_Due,ags9_Min_CMaxI_Due,agr9_Min_CMaxI_Due,ags12_Mean_CMaxI_Due,agr12_Mean_CMaxI_Due,ags12_Max_CMaxI_Due,agr12_Max_CMaxI_Due,ags12_Min_CMaxI_Due,agr12_Min_CMaxI_Due,ags3_Mean_CMaxC_Days,agr3_Mean_CMaxC_Days,ags3_Max_CMaxC_Days,agr3_Max_CMaxC_Days,ags3_Min_CMaxC_Days,agr3_Min_CMaxC_Days,ags6_Mean_CMaxC_Days,agr6_Mean_CMaxC_Days,ags6_Max_CMaxC_Days,agr6_Max_CMaxC_Days,ags6_Min_CMaxC_Days,agr6_Min_CMaxC_Days,ags9_Mean_CMaxC_Days,agr9_Mean_CMaxC_Days,ags9_Max_CMaxC_Days,agr9_Max_CMaxC_Days,ags9_Min_CMaxC_Days,agr9_Min_CMaxC_Days,ags12_Mean_CMaxC_Days,agr12_Mean_CMaxC_Days,ags12_Max_CMaxC_Days,agr12_Max_CMaxC_Days,ags12_Min_CMaxC_Days,agr12_Min_CMaxC_Days,ags3_Mean_CMaxC_Due,agr3_Mean_CMaxC_Due,ags3_Max_CMaxC_Due,agr3_Max_CMaxC_Due,ags3_Min_CMaxC_Due,agr3_Min_CMaxC_Due,ags6_Mean_CMaxC_Due,agr6_Mean_CMaxC_Due,ags6_Max_CMaxC_Due,agr6_Max_CMaxC_Due,ags6_Min_CMaxC_Due,agr6_Min_CMaxC_Due,ags9_Mean_CMaxC_Due,agr9_Mean_CMaxC_Due,ags9_Max_CMaxC_Due,agr9_Max_CMaxC_Due,ags9_Min_CMaxC_Due,agr9_Min_CMaxC_Due,ags12_Mean_CMaxC_Due,agr12_Mean_CMaxC_Due,ags12_Max_CMaxC_Due,agr12_Max_CMaxC_Due,ags12_Min_CMaxC_Due,agr12_Min_CMaxC_Due,ags3_Mean_CMaxA_Days,agr3_Mean_CMaxA_Days,ags3_Max_CMaxA_Days,agr3_Max_CMaxA_Days,ags3_Min_CMaxA_Days,agr3_Min_CMaxA_Days,ags6_Mean_CMaxA_Days,agr6_Mean_CMaxA_Days,ags6_Max_CMaxA_Days,agr6_Max_CMaxA_Days,ags6_Min_CMaxA_Days,agr6_Min_CMaxA_Days,ags9_Mean_CMaxA_Days,agr9_Mean_CMaxA_Days,ags9_Max_CMaxA_Days,agr9_Max_CMaxA_Days,ags9_Min_CMaxA_Days,agr9_Min_CMaxA_Days,ags12_Mean_CMaxA_Days,agr12_Mean_CMaxA_Days,ags12_Max_CMaxA_Days,agr12_Max_CMaxA_Days,ags12_Min_CMaxA_Days,agr12_Min_CMaxA_Days,ags3_Mean_CMaxA_Due,agr3_Mean_CMaxA_Due,ags3_Max_CMaxA_Due,agr3_Max_CMaxA_Due,ags3_Min_CMaxA_Due,agr3_Min_CMaxA_Due,ags6_Mean_CMaxA_Due,agr6_Mean_CMaxA_Due,ags6_Max_CMaxA_Due,agr6_Max_CMaxA_Due,ags6_Min_CMaxA_Due,agr6_Min_CMaxA_Due,ags9_Mean_CMaxA_Due,agr9_Mean_CMaxA_Due,ags9_Max_CMaxA_Due,agr9_Max_CMaxA_Due,ags9_Min_CMaxA_Due,agr9_Min_CMaxA_Due,ags12_Mean_CMaxA_Due,agr12_Mean_CMaxA_Due,ags12_Max_CMaxA_Due,agr12_Max_CMaxA_Due,ags12_Min_CMaxA_Due,agr12_Min_CMaxA_Due,act3_n_arrears,act3_n_arrears_days,act3_n_good_days,act6_n_arrears,act6_n_arrears_days,act6_n_good_days,act9_n_arrears,act9_n_arrears_days,act9_n_good_days,act12_n_arrears,act12_n_arrears_days,act12_n_good_days,act_cins_n_loans_act,act_cins_maxdue,act_cins_min_pninst,act_cins_min_lninst,act_cins_utl,act_cins_dueutl,act_cins_cc,act_cins_seniority,act_cins_min_seniority,act_cins_n_loans_hist,act_cins_n_statC,act_cins_n_statB,act_ccss_n_loans_act,act_ccss_maxdue,act_ccss_min_pninst,act_ccss_min_lninst,act_ccss_utl,act_ccss_dueutl,act_ccss_cc,act_ccss_seniority,act_ccss_min_seniority,act_ccss_n_loans_hist,act_ccss_n_statC,act_ccss_n_statB,act_cus_active,default3,default6,default12,decision,decline_reason
0,0000000625,css1975010100063,css,197501,55.0,0.629712,1.583782,3157.0,5000.0,24.0,2.0,1780.0,208.0,Empty,Female,Permanent,Maried,Small,Owner,Owner,0.629712,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1,N,998 not active customer
1,0000001330,css1975010100098,css,197501,45.0,0.326905,1.530456,3267.0,5000.0,24.0,3.0,860.0,208.0,Empty,Female,Permanent,Maried,Big,Owner,Owner,0.326905,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,N,998 not active customer
2,0000002179,css1975010100120,css,197501,42.0,0.538908,2.903600,1722.0,5000.0,24.0,1.0,720.0,208.0,Empty,Male,Permanent,Maried,Big,Rental,Owner,0.538908,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,N,998 not active customer
3,0000002366,css1975010100123,css,197501,70.0,0.559242,3.949447,1266.0,5000.0,24.0,0.0,500.0,208.0,Empty,Female,Retired,Maried,Medium,Owner,Owner,0.559242,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1,N,998 not active customer
4,0000000079,css1975010200009,css,197501,68.0,0.647492,3.344482,1495.0,5000.0,24.0,0.0,760.0,208.0,Empty,Male,Retired,Widowed,Big,Owner,Owner,0.647492,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,60.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,N,998 not active customer

In [16]:
def apply_bins(df, binning_maps) -> pd.DataFrame:
    """
    Apply fitted bin definitions to *any* dataset (train / valid / test).

    For every feature in binning_maps a new column ``{feature}_GRP`` is added
    containing a string group label.

    Numeric rules
    -------------
    * NaN              → "<MISSING>"  (or spec["missing_label"] if present)
    * finite value     → interval label built from edges, e.g. "(-inf, 7445.12]"

    Nominal rules
    -------------
    * NaN              → spec["missing_label"]
    * known category   → spec["category_map"][category]
    * unknown category → spec["other_label"]

    The original columns are left untouched.
    """
    new_cols = {}
    
    for feat, spec in binning_maps.items():
        grp_col = f"{feat}_GRP"

        if spec["type"] == "numeric":
            missing_label = spec.get("missing_label", "<MISSING>")
            edges = spec["edges"]

            cut = pd.cut(df[feat], bins=edges, include_lowest=True, right=True)
            new_cols[grp_col] = cut.astype(object).fillna(missing_label)

            # df.loc[pd.isna(df[feat]), grp_col] = missing_label
        elif spec["type"] == "nominal":
            cat_map = spec["category_map"]
            other_label = spec["other_label"]
            missing_label = spec["missing_label"]

            s = df[feat]
            mapped = pd.Series(other_label, index=s.index, dtype="str")
            missing_mask = pd.isna(s)

            norm = s.astype(str)
            mapped.loc[~missing_mask] = norm.loc[~missing_mask].map(cat_map).fillna(other_label)
            mapped.loc[missing_mask] = missing_label
            new_cols[grp_col] = mapped

        else:
            raise ValueError(f"Unknown bin type for feature {feat}: {spec['type']}")

    new_df = pd.DataFrame(new_cols, index=df.index)

    return pd.concat([df, new_df], axis=1)

train_binned = apply_bins(df_train, binning_maps)
valid_binned = apply_bins(df_valid, binning_maps)

grp_cols = [c for c in train_binned.columns if c.endswith("_GRP")]
display(train_binned[grp_cols].head())

,act_age_GRP,act_age_GRP,act_cc_GRP,act_cc_GRP,act_loaninc_GRP,act_loaninc_GRP,act_age_GRP,act_age_GRP,act_cc_GRP,act_cc_GRP,act_loaninc_GRP,act_loaninc_GRP
0,NaN,"(48.5, 57.5]",NaN,"(0.551, 0.638]",NaN,"(1.569, 2.38]",NaN,"(48.5, 57.5]",NaN,"(0.551, 0.638]",NaN,"(1.569, 2.38]"
1,NaN,"(-inf, 45.5]",NaN,"(0.314, 0.511]",NaN,"(0.673, 1.569]",NaN,"(-inf, 45.5]",NaN,"(0.314, 0.511]",NaN,"(0.673, 1.569]"
2,NaN,"(-inf, 45.5]",NaN,"(0.511, 0.551]",NaN,"(2.38, 4.771]",NaN,"(-inf, 45.5]",NaN,"(0.511, 0.551]",NaN,"(2.38, 4.771]"
3,NaN,"(57.5, 75.5]",NaN,"(0.551, 0.638]",NaN,"(2.38, 4.771]",NaN,"(57.5, 75.5]",NaN,"(0.551, 0.638]",NaN,"(2.38, 4.771]"
4,NaN,"(57.5, 75.5]",NaN,"(0.638, inf]",NaN,"(2.38, 4.771]",NaN,"(57.5, 75.5]",NaN,"(0.638, inf]",NaN,"(2.38, 4.771]"

In [ ]:
def build_woe_table(df_binned, feature_grp, target, epsilon) -> pd.DataFrame:
    """
    Compute goods / bads, WOE, and IV contribution for every bin of a
    grouped feature column.

    Parameters
    ----------
    df_binned   : DataFrame containing the grouped column and target.
    feature_grp : name of the grouped column, e.g. "app_income_GRP".
    target      : binary target column (1 = bad/default, 0 = good).
    epsilon     : small constant added to numerator/denominator to avoid
                  log(0) / division-by-zero when a bin has zero goods or bads.

    Returns
    -------
    DataFrame with one row per bin and columns:
        bin, n, goods, bads, dist_good, dist_bad, woe, iv_component
    """
    total_good = (df_binned[target] == 0).sum()
    total_bad = (df_binned[target] == 1).sum()

    grouped = (
        df_binned
        .groupby(feature_grp)[target]
        .agg(n="count", bads="sum")
        .reset_index()
        .rename(columns={feature_grp: "bin"})
    )

    grouped["goods"] = grouped["n"] - grouped["bads"]
    grouped["dist_good"] = (grouped["goods"] + epsilon) / (total_good + epsilon)
    grouped["dist_bad"] = (grouped["bads"] + epsilon) / (total_bad + epsilon)
    grouped["woe"] = np.log(grouped["dist_good"] / grouped["dist_bad"])
    grouped["iv_component"] = (grouped["dist_good"] - grouped["dist_bad"]) * grouped["woe"]

    return grouped

woe_table = build_woe_table(train_binned, "act_age_GRP", "default12", SCORECARD_PARAMS["woe_epsilon"])
display(woe_table)
assert {"bin", "woe", "iv_component"}.issubset(woe_table.columns)

In [ ]:
# Fit on full selected features (not sample slice)
all_features = cand["all"]   # or cand["ins"] / cand["css"] depending on scorecard
binning_maps = fit_binning_maps(df_train, all_features, "default12", SCORECARD_PARAMS)

# Apply to train/valid
train_binned = apply_bins(df_train, binning_maps)
valid_binned = apply_bins(df_valid, binning_maps)

grp_cols = [c for c in train_binned.columns if c.endswith("_GRP")]
print("n grp cols:", len(grp_cols), "expected:", len(all_features))
display(train_binned[grp_cols].head())